# Generated by Django 4.2.2 on 2023-08-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newws_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('message', models.TextField(max_length=15000)),
            ],
        ),
    ]
