# Generated by Django 4.2.2 on 2024-02-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newws_app', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
