# Generated by Django 4.2.2 on 2024-02-29 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newws_app', '0004_news_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
    ]
